<table class="table">
    <thead>
    <tr>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Возраст</th>
        <th>Город</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Александр</td>
        <td>Иванов</td>
        <td>25</td>
        <td>Москва</td>
    </tr>
    <tr>
        <td>Елена</td>
        <td>Смирнова</td>
        <td>32</td>
        <td>Санкт-Петербург</td>
    </tr>
    <tr>
        <td>Дмитрий</td>
        <td>Петров</td>
        <td>41</td>
        <td>Новосибирск</td>
    </tr>
    </tbody>
</table>
